"""Add description to models

Revision ID: 709928329178
Revises: 56d643fb858d
Create Date: 2018-04-14 00:44:24.925535

"""

# revision identifiers, used by Alembic.
revision = '709928329178'
down_revision = '56d643fb858d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'description')
    op.drop_column('departments', 'description')
    # ### end Alembic commands ###
